id: D1D559D14
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:09:08+00:00'
last_modified: '2022-05-26T11:51:41.078539+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    73af:
      image_group_id: I1PD95879
      title: ངན་སོང་ཐམས་ཅད་ཡོངས་སུ་སྦྱོང་བའི་རོའི་སྦྱིན་སྲེག་གི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག།
      total_pages: 1734
      order: 34
      base_file: 73af.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
