id: 909a45ce32af4030998f9cbf229af407
initial_creation_type: ocr
source_metadata:
  volumes:
    d506043b9b654e649191f150d946768a:
      base_file: v034.txt
      image_group_id: I1PD95879
      title: ངན་སོང་ཐམས་ཅད་ཡོངས་སུ་སྦྱོང་བའི་རོའི་སྦྱིན་སྲེག་གི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག།
      total_pages: 1734
      volume_number: 34
